post_install() {
	glib-compile-schemas /usr/share/glib-2.0/schemas/
}

post_upgrade() {
	post_install
	instructions
}

post_remove() {
	post_install
	instructions
}

instructions() {
	echo "==> ****************************************************"
  	echo "==> Don't forget to restart GNOME Shell ([Alt]+[F2], r) "
  	echo "==> and to enable the extension with the tweak tool.    "
	echo "==> ****************************************************"
}
